### ISSUE TITLE
Show a conflict of the sessions in My Schedule if any

### ISSUE THREAD

**Issue by hkurokawa** [konifar/droidkaigi2016#101]
Just an idea but I am wondering it might be convenient to notice user if there are any sessions of which time slots are overlapped.

**Comment by jmatsu** [comment]
Already created this patch? Or in progress?

I created this patch 10 minutes ago. :sob:

**Comment by hkurokawa** [comment]
@jmatsu Ah, I didn't do anything yet. Please create a PR for this issue!

**Comment by konifar** [comment]
Guess nobody started.
Awesome! Feel free to send PR.

**Comment by jmatsu** [comment]
Thanks! I'll send a PR soon.
