### ISSUE TITLE
Improve readability of colored strings

### ISSUE THREAD

**Issue by jmatsu** [konifar/droidkaigi2016#103]
It is hard to read yellow strings if the background color is white.
The description area of the session page has this state.

It should be changed to another color.

Shown in the bottom of the following image (Master of Canvas by Yuki Mima):

<img src="https://raw.githubusercontent.com/jmatsu/LightResources/a3ee07af1eab28563ceb2fd5bba8b380825661e2/reports/droidkaigi/hard_to_read_yellow_string.png" width="300px" alt="hard_to_read_yellow_string">

**Comment by konifar** [comment]
:eyes: 
Thanks for report. Just confirmation, is your os version is above 6.0?

**Comment by jmatsu** [comment]
I'm sorry. I forgot to write it.

Device Information:
Device: SOL22 (Xperia UL)
OS Version:  4.2.2

Application Information:
No.26 (latest now)

**Comment by konifar** [comment]
Themes.xml is not good. Maybe accent color will be changed.
Thanks!

**Comment by punchdrunker** [comment]
I fixed it in #110.
