### ISSUE TITLE
Revise README a bit

### ISSUE THREAD

**Issue by shaunkawano** [konifar/droidkaigi2016#105]
I'd like to revise README.md file just for a tiny bit for tiny improvement.

**Comment by konifar** [comment]
@shaunkawano Oh thanks, because my English is poor :cry: 
So feel free to submit PR!

**Comment by shaunkawano** [comment]
@konifar Thank you very much for your comment!

> Oh thanks, because my English is poor :cry: 

Nono please trust that I do not mean like that at all and please do not take this issue too seriously; I 
asked punch-san on Twitter if I can help something and all I can do is something like this.. orz 

> So feel free to submit PR!

Thank you, and, feel free to comment or ask anything on my PR as well!

**Comment by konifar** [comment]
:+1:

**Comment by shaunkawano** [comment]
I've fixed this issue in #106 and #111 so I'll close this issue.
