### ISSUE TITLE
wrong session detail information

### ISSUE THREAD

**Issue by mhidaka** [konifar/droidkaigi2016#117]
The session "パ明日、敗訴しないためのセキュアコーディング" detail is "対象：Clean Archite..." but It does not match the session title

this report from α-tester umetsu_kentaro, thankyou!

**Comment by mhidaka** [comment]
fixed 
https://github.com/konifar/droidkaigi2016/pull/116#issuecomment-182246716

**Comment by hotchemi** [comment]
It's already fixed
