### ISSUE TITLE
Language settings should display language names in each language

### ISSUE THREAD

**Issue by atsushieno** [konifar/droidkaigi2016#124]
Right now the language dialog looks like:

○英語
◎日本語
○アラビア語
　[キャンセル][OK]

But if you cannot read Japanese, you cannot choose the right language.

Almost all people can still read "OK", but if you switch to Arabic and open this dialog, you'd have no idea which is which.

So, the right implementation should be:

○English
◎日本語
○العربية

... and probably immediately apply the translated strings on [OK] and [Cancel] when a language was chosen. That's what Android Settings app does.

**Comment by konifar** [comment]
I agree with you. I'll fix. Thanks a lot!!
