### ISSUE TITLE
Arabic is shown when English is selected as current language

### ISSUE THREAD

**Issue by atsushieno** [konifar/droidkaigi2016#126]
The latest master (I confirmed with c4acbd0) does not show English messages even if I choose English. It shows Arabic instead. Japanese and Arabic are displayed as expected.

Confirmed on both my English-based device (XperiaZ3) and x86 emulator in SDK tools 25.0.5.

**Comment by konifar** [comment]
Oh really? Very sorry... I'll check it. Thanks for your report :bow:

**Comment by mhidaka** [comment]
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/res/raw/sessions_en.json
replaced by Arabic resource

**Comment by konifar** [comment]
:scream_cat: I'll fix soon.

**Comment by atsushieno** [comment]
:+1:

**Comment by konifar** [comment]
Fixed.
