### ISSUE TITLE
Improve session feedback design

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#158]
https://deploygate.com/distributions/0d34ff6b3ccedf2a76771d9b6002c55b4f0aac1f/comments/4743

> マテリアルデザイン！！
> フィードバック画面の質問が埋もれてわかりにくいのがもったいないので、各評価するエリアをカード系にするか、区切り線をひくか、質問の文字濃くする or 1-2sp でかくする、みたいなのしたいです。

**Comment by hkurokawa** [comment]
Good. Let's try to do that in the next release. :+1:
