### ISSUE TITLE
Contributors credit page

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#169]
I want all contributors credit page

<img width="355" alt="2016-02-03_11_26_43_png" src="https://cloud.githubusercontent.com/assets/1269214/13023864/8c18536e-d230-11e5-9555-1e57c10c3b9c.png">

**Comment by hotchemi** [comment]
Completely agree:D

**Comment by konifar** [comment]
More fun :+1:

**Comment by gotokatsuya** [comment]
Looks good. I will try.

**Comment by konifar** [comment]
Oh, really?! Cool! I'm so happy!

**Comment by gotokatsuya** [comment]
Yes, Leave it to me !
