### ISSUE TITLE
Release Ver 1.0.1

### ISSUE THREAD

**Issue by hkurokawa** [konifar/droidkaigi2016#172]
- [x] Increment the verision code
- [x] Increment the version number

**Comment by konifar** [comment]
Fix only here :)
https://github.com/konifar/droidkaigi2016/blob/master/app/build.gradle#L11

**Comment by hkurokawa** [comment]
I just noticed that. Great!

**Comment by konifar** [comment]
This is inspired by u2020.
https://github.com/JakeWharton/u2020/blob/master/build.gradle#L88-L89
