### ISSUE TITLE
Fix feedback send bug

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#191]
When I tap feedback send button, shown the error message `Sorry. Currently we are not accepting the feedback. You can submit feedback only during the event dates.`.

It might be not expected error message.

**Comment by hotchemi** [comment]
@hkurokawa might knows the answer.

**Comment by hkurokawa** [comment]
Oh, guys, sorry for not explaining about that.  It is as expected.

I am currently stopping all the feedbacks (you have a button on the Google form to enable/disable it). If you would like to try that, please let me or other committee member know. We can enable the form for a while.  Or do you think it is better to enable that from now on?

Anyway, sorry for confusing you.

**Comment by konifar** [comment]
I see! Thanks for your explanation. So close it.
