### ISSUE TITLE
Add repository link.

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#200]
<img width="364" alt="2016-02-13_17_49_28_png" src="https://cloud.githubusercontent.com/assets/1269214/13029094/c427850a-d2c5-11e5-8a8d-931d018b7b3d.png">

**Comment by konifar** [comment]
I guess it is good text `GitHub Repository`.

**Comment by konifar** [comment]
Maybe you can use `AppUtil.showWebPage()` :)

**Comment by syarihu** [comment]
I will try!

**Comment by konifar** [comment]
Cool! Thanks!
