### ISSUE TITLE
Favorite button doesn't return original scale

### ISSUE THREAD

**Issue by kaelaela** [konifar/droidkaigi2016#206]
![device-2016-02-14-031234](https://cloud.githubusercontent.com/assets/3871115/13029233/7117487e-d2c9-11e5-90cf-16c62a502d20.png)

When I press the favorite button and slide to outside of CardView, it does not return original scale.
I tried to fix it, sorry, but I couldn't. It seems to not call ACTION_UP touch event！

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
It seems complex issue. it might be LikeButton, UI library issue.
Anyway, thanks for your report!
