### ISSUE TITLE
Create inquiry form in English.

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#220]
@hkurokawa English version not exists?
https://docs.google.com/forms/d/1fpxZOqprZyzBgMBb7HCCrq538oOzfzWkOMpItRqF-ro/viewform

**Comment by hotchemi** [comment]
I think this link is.
https://docs.google.com/forms/d/1X9x9eb92_BeRaELjePq8FgeqTa70MyChkmUWFce47jo/edit

**Comment by hkurokawa** [comment]
@konifar Sorry for the late reply. As hotchemi already pointed out, there is a form but not translated yet. As for now, we can just use the URL and update it later.
