### ISSUE TITLE
Improve touch area / feedback of social icons on detail("詳細") page

### ISSUE THREAD

**Issue by shaunkawano** [konifar/droidkaigi2016#237]
<img width="500" alt="2016-02-15 7 52 31" src="https://cloud.githubusercontent.com/assets/920911/13046720/d7a6f648-d41d-11e5-81bb-3e1d76806683.png">

**Comment by hotchemi** [comment]
@shaunkawano Could u send a PR?

**Comment by shaunkawano** [comment]
I will! Hopefully I can get this done till the end of the day; is that ok?

**Comment by hotchemi** [comment]
Sure! Really appreciated!
