### ISSUE TITLE
Add session data

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#240]
Key note description at 2/19 10:00~ is empty.

<img width="327" alt="2016-02-15_11_23_08_png" src="https://cloud.githubusercontent.com/assets/1269214/13048406/fb5e8226-d428-11e5-97fa-ce79336d6f2f.png">

**Comment by hotchemi** [comment]
CC: @yaraki

**Comment by mhidaka** [comment]
I got keynote description from Araki-san

```
Android アプリを開発している方であればいずれかのサポート ライブラリを使ったことがあるでしょう。各サポート ライブラリをざっと紹介した上で、よく聞かれる質問にお答えしつつ、Design ライブラリの新機能や開発の裏側などもお伝えしたいと思います。
```
