### ISSUE TITLE
Add inquiry url

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#27]
Inquiry button is already created.

<img width="270" alt="2016-02-03_11_26_43_png_and_new_issue_ _konifar_droidkaigi2016" src="https://cloud.githubusercontent.com/assets/1269214/12780959/a3ac7b64-cab4-11e5-9d6c-629f616ed803.png">

Add inquiry web page open logic in `AboutFragment`.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/fragment/AboutFragment.java#L67-L69

**Comment by hkurokawa** [comment]
Thinking of opening the Google Form with a WebView/ChromeTab.  Is that fine?

**Comment by konifar** [comment]
@hkurokawa Yes, I think ChromeTab is better. AppUtil class has util method.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/util/AppUtil.java#L141-L148

```java
public static void showWebPage(Activity activity, @NonNull String url) {
    CustomTabsIntent intent = new CustomTabsIntent.Builder()
            .setShowTitle(true)
            .setToolbarColor(ContextCompat.getColor(activity, R.color.theme500))
            .build();

    intent.launchUrl(activity, Uri.parse(url));
}
```

**Comment by hkurokawa** [comment]
Great :+1: Seems I have nothing to do here :sunglasses:
