### ISSUE TITLE
Retrolambda breaks lint

### ISSUE THREAD

**Issue by Nkzn** [konifar/droidkaigi2016#290]
`./gradlew lint` has many many errors. (related: https://github.com/evant/gradle-retrolambda/issues/96 )

If we want to remove lint errors, the [android-retrolambda-lombok](https://github.com/evant/android-retrolambda-lombok) may help us. However, this is "[experimental fork](https://github.com/evant/gradle-retrolambda#lint-fails-on-java-files-that-have-lambdas)", evant says.

**Comment by konifar** [comment]
Thanks for your suggestion! I know this issue... To be honest, I don't know retrolambda-lombok is stable or not. So I want more information. Anybody help? :bow:
