### ISSUE TITLE
Is this someone's personal Google API Key?

### ISSUE THREAD

**Issue by ken5scal** [konifar/droidkaigi2016#315]
Hi, I was reading DroidKaigiClient.java codes for my future references, and I thought it would be better not to make your personal API Key public if it is the case. Guessing from annotation, could it be yours @hkurokawa ?

```DroidKaigiClient.java
public interface GoogleFormService { //line103
```

**Comment by mstssk** [comment]
Is this you're mention? [DroidKaigiClient.java#L104](https://github.com/konifar/droidkaigi2016/blob/8c3a9d8a1e17756a4f495dd9ad8352f9c3889c4d/app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java#L104)
This is not API key. This is URL path to post Google form for Session feedback.

**Comment by ken5scal** [comment]
Oh, sorry for confusion. I will close this issue.

**Comment by konifar** [comment]
@ken5scal Thanks for your report! :+1: 

@mstssk Thanks! Your reply help me so much! :bow:
