### ISSUE TITLE
SettingFragment loses its elevation setting

### ISSUE THREAD

**Issue by ken5scal** [konifar/droidkaigi2016#321]
* Go Setting from menu  (or sponsor, or any other fragments without tablayout)
* send activity on background
* pull activity to foreground
* shadow under toolbar is gone

# Before
![image](https://cloud.githubusercontent.com/assets/9734362/13273678/9a205a90-dae8-11e5-8481-47a15664052e.png)

# After
![image](https://cloud.githubusercontent.com/assets/9734362/13273673/8eb2b0b8-dae8-11e5-856c-9a37bf62ac91.png)

**Comment by konifar** [comment]
Thanks for your report. I didn't notice it.
