### ISSUE TITLE
[Discuss] Adopt Kotlin

### ISSUE THREAD

**Issue by hotchemi** [konifar/droidkaigi2016#329]
Folks, how do you think about of it? :smile:

**Comment by konifar** [comment]
Absolutely agree. Have more fun! :smiley:

**Comment by hkurokawa** [comment]
:+1:
One comment. I think it is better to use Kotlin as long as we could if we decided using Kotlin. I mean, a hybrid of Kotlin and Java will look just ugly and, to have more fun, I feel like I am trying that all-Kotlin project.

How do you guys think about it? Besides, I am concerning about all the libraries provide Kotlin version or not.

**Comment by hotchemi** [comment]
Uh, just remembered Kotlin 1.0 and DataBinding don't work well together now... :cry: 

https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FKT-8007

**Comment by konifar** [comment]
Yes, I guess Taro=san recommended [kotterknife](https://github.com/JakeWharton/kotterknife).

**Comment by hotchemi** [comment]
And, PermissionsDispatcher doesn't work well neither because it uses Kotlin for processor module... :crying_cat_face:

**Comment by hkurokawa** [comment]
Hmm. What do you mean? You mean if we are using PermissionDispatcher, just a piece of Kotlin code in the app doesn't work? I suppose after the code is generated, it doesn't matter whether the app is in Java or Kotlin.

**Comment by hotchemi** [comment]
Ah sorry! If we are gonna remove DataBinding, everything is fine :santa:

**Comment by hkurokawa** [comment]
I see. Thank you for your clarification. :ok_woman:

**Comment by hotchemi** [comment]
And guess we should create `kotlin` branch, and gonna dive into Kotlin world!

**Comment by konifar** [comment]
Agree.

> And guess we should create kotlin branch, and gonna dive into Kotlin world!

**Comment by rejasupotaro** [comment]
Vote for creating `kotlin` branch.
I wanted to use Kotlin somewhere before introducing Kotlin in production :rocket:

**Comment by hotchemi** [comment]
No going back :rocket: :rocket: :rocket:
