### ISSUE TITLE
Fix en strings.xml

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#33]
Now en strings.xml is not good. I want to check to someone who can speak English well :wink:

**Comment by hkurokawa** [comment]
@KeithYokoma Maybe we can just close the issue now or changing the milestone to 1.1.0? Let me know your idea.

**Comment by KeithYokoma** [comment]
DroidKaigi description seems not to be up-to-date. I will update it!

**Comment by KeithYokoma** [comment]
looks good to me!
