### ISSUE TITLE
Improve Korean text

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#332]
Great Korean engineer suggested to improve korean text. https://github.com/konifar/droidkaigi2016/pull/331

**Comment by hotchemi** [comment]
We're global:D

**Comment by Pluu** [comment]
Gooood.
Thanks support korean language.
I'll fix `raw/sessions_ko.json`.

**Comment by konifar** [comment]
@Pluu Thanks! Could you send pull request? :bow:

**Comment by Pluu** [comment]
fixed `raw/sessions_ko.json` translation : #336

**Comment by konifar** [comment]
@Pluu has already improved! Great work! Thanks 👏
