### ISSUE TITLE
Change toolbar color in my schedule page

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#35]
My schedule page is very similar to All sessions page. It make user confused.
So I want to change toolbar and statusbar color.

**Comment by hotchemi** [comment]
Any thoughts?

**Comment by konifar** [comment]
I could change toolbar color, but I could not change statusbar color with transparecy...

<img width="445" alt="2016-02-03_12_13_18_png" src="https://cloud.githubusercontent.com/assets/1269214/12972820/9cded524-d0eb-11e5-808f-4d14f3128586.png">
