### ISSUE TITLE
How to develop android using java8?

### ISSUE THREAD

**Issue by cinabro88** [konifar/droidkaigi2016#357]
Hi. I'm Korean Android Developer.

I know that android don't support java8 yet. 
But I saw that this project use java8 in Readme.
Is it really??

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Hi @cinabro88 !
Exactly, it is not pure Java8. We use [retrolambda](https://github.com/orfjackal/retrolambda), backport of Java 8's lambda expressions to Java 7.
So we can use only lambda and method reference, can not use stream api and other functions of Java8.
