### ISSUE TITLE
Introduce MVVM or MVP?

### ISSUE THREAD

**Issue by hotchemi** [konifar/droidkaigi2016#382]
## Overview

Nowadays a bunch of Android developers are eager to discuss what kind of architecture we should adopt. I think this is the good timing to introduce MVVM or MVP to this app :D
The diff will be so huge, hence it might be better to create new architecture branch and work on it.
I have no strong opinion for MVP and MVVM...what do you think @konifar ?

**Comment by konifar** [comment]
Good issue 👍 
In my opinion, MVVM is better because Android have DataBinding now.
Android DataBinding is really similar to XAML on Microsoft. It fit well to MVVM architecture.

So I'll try it on architecture branch 😃

**Comment by hotchemi** [comment]
Here we go!!!!!!!!!!!

**Comment by amay077** [comment]
Sounds great!

I came from .NET/Xamarin world.
I strongly believe MVVM is best solution for mobile(Android / iOS / Win) apps design.

I made sample apps that is adopting MVVM pattern and using Rx.

* [Android Data Binding + MVVMパターンのサンプルを書いてみた - Qiita](http://qiita.com/amay077/items/b5c788bb3ee9ff84d9b4) 

Please check it!

**Comment by hotchemi** [comment]
@amay077 @konifar I created the brunch, here we go!!!!!!!!

https://github.com/konifar/droidkaigi2016/tree/mvvm

**Comment by hotchemi** [comment]
Let me close this issue since it's been a long time.

**Comment by konifar** [comment]
Thanks! We'll try MVVM on 2017 app

**Comment by amay077** [comment]
Yep.
I hope contribute to 2017 app 👍

**Comment by hotchemi** [comment]
Here we go!
