### ISSUE TITLE
Add splash page

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#52]
Cool splash is cool :smiley:

**Comment by hotchemi** [comment]
Guess it's not needed because our app is so fast to launch, not massive and slow :innocent: 

- [Launch screens - Patterns - Google design guidelines](https://www.google.com/design/spec/patterns/launch-screens.html#)

**Comment by konifar** [comment]
I see. You are right.
I considered in the case of low network env when the user open first time.

But it is not necessary now as you said.

**Comment by konifar** [comment]
Close it because it is not required.
