### ISSUE TITLE
Prepare more small speaker image

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#55]
Now speaker icon image size is so big.

**Comment by hotchemi** [comment]
Hmm, I'm thinking we can use glide's bitmap pool but...

**Comment by hkurokawa** [comment]
@konifar Just to confirm.  Are you concerning about the size of .apk file or memory usage?

**Comment by konifar** [comment]
@hkurokawa I am concerning about memory usage and time to load.

**Comment by hkurokawa** [comment]
I see.  Thank you.

Now I feel like preparing alternative image resources might be hard for Ver 1.0. And I am wondering adding a code like below resizing the image properly can reduce memory usage (though the loading time might not be changed...) and it might be acceptable for the Ver 1.0 release.  How do you think?

```java
            Picasso.with(imageView.getContext())
                    .load(imageUrl)
                    .resizeDimen(imageWidth, imageHeight)
                    .placeholder(R.drawable.ic_speaker_placeholder)
                    .error(R.drawable.ic_speaker_placeholder)
                    .transform(new CropCircleTransformation())
                    .into(imageView);
```

**Comment by konifar** [comment]
> I feel like preparing alternative image resources might be hard for Ver 1.0.

Hmm, I see.

And your suggestion `.resizeDimen(imageWidth, imageHeight)` sounds good!

**Comment by hkurokawa** [comment]
Great! I created another issue #89 for that solution and will keep this issue for future as the context is slightly different from the original.

**Comment by hotchemi** [comment]
I think we can close this issue. It's so tough to prepare each speaker's img again...

**Comment by konifar** [comment]
@hotchemi I agree with you. OK! Close it!
