### ISSUE TITLE
Add push notification feature

### ISSUE THREAD

**Issue by hotchemi** [konifar/droidkaigi2016#61]
## What

It might be better to add push notification feature. For example, We might want to notify participants to some message urgently.
Of course we don't have to have high priority for it.

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
I see. It's good. Unfortunately, Parse.com is dead :cry:

**Comment by hotchemi** [comment]
Oh boy...

**Comment by hkurokawa** [comment]
I think it is a great-to-have feature and will take some amount of time.  So I will not include this feature in Ver 1.1.0 release.  Of course, if you want, you can implement it anytime. :wink:

**Comment by konifar** [comment]
http://qiita.com/punchdrunker/items/49e0813ea4ad2caf7b55

**Comment by hotchemi** [comment]
I'm gonna close this issue cuz there is no concrete plan here.
