### ISSUE TITLE
Create a server program to accept session feedback request

### ISSUE THREAD

**Issue by hkurokawa** [konifar/droidkaigi2016#68]
This is a dependent of #32 Add feedback function.

Create a server program which accepts a session feedback request like below:

```
POST https://droidkaigi.jp/feedback

{
  "sessionId": 1,
  "ratingValuability": 2,
  "ratingContents": 3,
  "ratingSpeaker": 3,
  "comment": "Good. But not best IMO."
}
```

## Requirements
- Can process ~50 req/sec
- Average response time is less than 200 msec
- Should be working for 4 days, from 18th Feb to 21th Feb
- Data should be stored so that it can be summarised for each session later.
- The size of comment is less than 1.2KB (400 characters in Japanese)

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Should commen have max langth?

**Comment by konifar** [comment]
The api looks good for me :smiley:

**Comment by hkurokawa** [comment]
Great point! Added that limitation.

**Comment by konifar** [comment]
Thanks!
And I think `sessionId` should have INDEX.

**Comment by hotchemi** [comment]
@hkurokawa @konifar 

Just created sample. Please check readme. 3 minutes cooking:D

https://github.com/hotchemi/feedback-api

**Comment by konifar** [comment]
:eyes:
Thanks! I'll check it later.

**Comment by konifar** [comment]
Sounds good way
http://blog.blundellapps.co.uk/tut-send-app-data-to-a-web-spreadsheet-google-sheets/

**Comment by konifar** [comment]
Close this issue because we use google apps
