### ISSUE TITLE
Remove back button confirmation

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#80]
<img width="311" alt="2016-02-08_05_17_27_png" src="https://cloud.githubusercontent.com/assets/1269214/12878887/e07083b6-ce6e-11e5-8c4f-8d53c535832b.png">

Remove `onBackPressed()` override in MainActivity.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java#L100-L118

And manage Fragment backstack.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/activity/MainActivity.java#L85-L92

Like this.
1. Show All Sessions page.
2. Show Map page.
3. Press back button.
4. Back to All Sessions page.

**Comment by KeithYokoma** [comment]
already removed
