### ISSUE TITLE
Reopen app after language settings changed.

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#82]
Remove snackbar confirmation.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java#L93-L100

**Comment by hotchemi** [comment]
I guess title and detail say different stuff, which is correct?

**Comment by KeithYokoma** [comment]
I think I'm in charge of removing snackbar confirmation so the title is correct.

**Comment by hotchemi** [comment]
Gotcha.

**Comment by konifar** [comment]
Sorry, description is correct. 

When the user change language, snackbar is shown as confirmation to restart app. I guess confirmation is not necessary, so want to remove snackbar.

**Comment by KeithYokoma** [comment]
oh i c

**Comment by hotchemi** [comment]
Created PR.

**Comment by konifar** [comment]
Great thanks!
