### ISSUE TITLE
Prepare GooglePlayStore resources

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#87]
# Images
* Icon
* Cover image
* Promotion image

![_-_a_-_google_play_developer_console](https://cloud.githubusercontent.com/assets/1269214/12885711/77328218-ceab-11e5-90dd-25f1c5f0f1fd.png)

# Data
* Website url
* Mail address
* Phone number

![_-_a_-_google_play_developer_console](https://cloud.githubusercontent.com/assets/1269214/12885768/ce153792-ceab-11e5-9904-c6a4de8036fe.png)

**Comment by hotchemi** [comment]
Is it already done right?

**Comment by hkurokawa** [comment]
Done.  Thank you for your reminding me of this.  I am closing it.
