### ISSUE TITLE
Publish at Google Play

### ISSUE THREAD

**Issue by hkurokawa** [konifar/droidkaigi2016#88]
## Dependency
#87 Prepare GooglePlayStore resources

## Contents
- [x] Generate and store keystore somewhere secure
- [x] Build the release build
- [x] Write down the description
- [x] Upload screenshots and banner
- [x] Press Publish Button!

**Comment by konifar** [comment]
:+1:

**Comment by konifar** [comment]
@hkurokawa Great work! Thanks!
