### ISSUE TITLE
Notify session's start and end

### ISSUE THREAD

**Issue by hotchemi** [konifar/droidkaigi2016#91]
## What

It would better to add a feature that notify user to start and end of the session. And user can turn on and off it from setting.

Sample is the following. https://play.google.com/store/apps/details?id=pl.droidcon.app

### Start

Notify users 5 minutes before their favourite session's start. When users tap the notification, detail page will open.

### End

After 5 minutes of session's end, Notify users to send feedback to each speaker.

**Comment by hkurokawa** [comment]
Sounds great! I am adding Ver 1.1.0 flag to see if we can finish it before the release.

**Comment by TakafumiNanao** [comment]
memo:

* I'm going to use AlermManager.
* Be careful if notification works also after reboot.
* Hints on AlarmManager :arrow_right:  http://y-anz-m.blogspot.jp/2011/03/alarmmanager.html
* Done is better than perfect

**Comment by punchdrunker** [comment]
memo:

I'm going to use AlarmManager.
Be careful if notification works also after reboot.
Hints on AlarmManager :arrow_right: http://y-anz-m.blogspot.jp/2011/03/alarmmanager.html
Done is better than perfect
