### ISSUE TITLE
Add analytics events for each sponsor's link

### ISSUE THREAD

**Issue by hotchemi** [konifar/droidkaigi2016#93]
## What

Add analytics events for each sponsor's link.

## Why

It would help us explain new candidates to how DroidKaigi is great and it's worth to sponsor.

**Comment by konifar** [comment]
:eyes: Sounds good.

**Comment by konifar** [comment]
You can use `AnalyticsUtil` like this.

```java
@Inject
AnalyticsUtil analyticsUtil;

...

private void sendEvent(String sponsorUrl) {
    analyticsUtil.sendEvent("sponsor", sponsorUrl);
}
```

**Comment by punchdrunker** [comment]
I will do that

**Comment by konifar** [comment]
Thanks!!

**Comment by hotchemi** [comment]
Btw, I think AnalyticsUtil class name is kinda wired, cuz utils class shouldn't have its state right? I guess it would be great if it's like `Manager`.

**Comment by konifar** [comment]
> cuz utils class shouldn't have its state right?

Hmm, it is right.

But I don't like the class name '~Manager', because `~Manager` class tend to be fat. So `AnalyticsTracker` or something may be better I guess.

**Comment by hotchemi** [comment]
Totally. You have a good point!

**Comment by TakafumiNanao** [comment]
How is AnalyticsHelper?

**Comment by yiino-cq** [comment]
:+1: `Helper` is easy-listening

**Comment by punchdrunker** [comment]
How is AnalyticsHelper? (resend because I have posted a comment with my company account...)

**Comment by ytRino** [comment]
Sounds good (wrong account, me too:persevere:)

**Comment by konifar** [comment]
`AnalyticsHelper` is also good. But I prefer `AnalyticsTracker`, because it is more clear the role of this class. how do you think?

**Comment by ytRino** [comment]
I don't have strong opinion for that. AnalyticsTracker is reasonable too.

**Comment by hotchemi** [comment]
+1 for AnalyticsTracker

**Comment by punchdrunker** [comment]
thx!

**Comment by punchdrunker** [comment]
done!
